name: End-to-End Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Ensure this matches the version required by your Netlify CLI
      - name: Create .env.local file
        run: |
          echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} >> .env.local
          echo MONGODB_ATLAS_URI=${{ secrets.MONGODB_ATLAS_URI }} >> .env.local
          echo NODE_ENV=development >> .env.local

      - name: Install project dependencies
        run: npm install

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Start Vercel server in the background
        run: vercel dev & # &> vercel.log &
        shell: bash

      - name: Wait for Vercel server to be ready
        run: |
          until curl --output /dev/null --silent --head --fail http://localhost:3000; do
            echo "Waiting for Vercel server..."
            sleep 5
          done

      - name: Run Cypress tests
        run: npm run cypress:run
        env:
          CI: true

      - name: Upload Cypress screenshots
        if: failure() # Only upload screenshots if the job failed
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: cypress/screenshots/

      - name: Upload Vercel logs
        uses: actions/upload-artifact@v2
        if: always() # or use `failure()` to upload only if the job fails
        with:
          name: vercel-logs
          path: vercel.log
